name: Run Tests on PR



on:
  pull_request:
    branches:
      - ${{ github.event.pull_request.head.ref }}



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm run test
